### PR TITLE
Dialoguemd/add props to channel extra member

### PR DESCRIPTION
**Pull request by vicrep**

### CODE REVIEW

**Comment by vicrep** [comment]
@hugoduncan this was locally validated and tested

**Comment by vicrep** [comment]
screen shot 2017-07-21 at 2 05 58 pm

**Comment by hugoduncan** [comment]
@vicrep please add an issue to dialoguemd/mattermost-app to filter the props to just show the picture.

**Comment by vicrep** [comment]
@hugoduncan done: https://github.com/dialoguemd/mattermost-service/issues/29

**Pull request merged**
